version: '3.8'

services:
  api:
    build: .
    container_name: fastapi_numbers_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: mongodb://admin:admin123@mongodb:27017/numbers_db
      MONGO_DB_NAME: numbers_db
      APP_ENV: production
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app_network

  mongodb:
    image: mongo:7.0
    container_name: mongodb_numbers_api
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: numbers_db
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/numbers_db --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_ui
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app_network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  app_network:
    driver: bridge
